name: Docker Image CI (PR)

on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  build:
    strategy:
        matrix:
          pytorch_date: [ "22.12", "22.11" ]
          mmcv_version: [ "1.7.1", "1.7.0", "1.6.2", "1.6.1", "1.6.0", "1.5.3", "1.5.2" ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.1.0
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.2.1
      
    - name: Docker Login
      if: success()
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        tags: mmdet:torch${{ matrix.pytorch_date }}-mmcv${{ matrix.mmcv_version }} 
        push: false
        build-args: |
          PYTORCH=${{ matrix.pytorch_date }} 
          MMCV_VERSION=${{ matrix.mmcv_version }} 